TeamFranka/affinity

README.md

Update for CLA

---

package-lock.json
package.json
src/components/activity.vue
src/components/edit-poll.vue
src/components/poll.vue
tests/e2e/specs/polls.js
tests/e2e/support/commands.js

More tests for polls

---

backend/cloud/models/team.js
backend/cloud/user.js
src/components/login-modal.vue
src/components/login.vue
src/components/my-menu.vue
src/db/schemas/team.ts
src/views/Me.vue
tests/e2e/specs/polls.js
tests/e2e/specs/signup.js

Automatic membership on signup

---

backend/cloud/installation.js
bin/mock-data.js
bin/mock-data/index.ts
src/components/anon-menu.vue
src/components/footer-menu.vue
src/components/settings/push-notification.vue
src/stores/auth.ts
src/utils/camera.ts
src/utils/env.ts
src/utils/setup.ts
src/views/settings/Notifications.vue
tests/e2e/specs/notifications-configuration.js

New installation management with UI

---

backend/Dockerfile
backend/cloud/installation.js
backend/cloud/objects.js
backend/cloud/package-lock.json
backend/cloud/package.json
bin/mock-data.js
bin/mock-data/index.ts
docker-compose.yml
package-lock.json
package.json
src/components/activity.vue
src/components/new-post.vue
src/stores/draft.ts
tests/e2e/specs/simple-post.js

Replacing link embed functionalilty

---

src/components/activity.vue
src/components/generic/selector.vue
src/components/new-post.vue
src/stores/auth.ts
src/views/Feed.vue
tests/e2e/specs/multi-team-posting.js
tests/e2e/specs/simple-post.js

Adding test to select other team (than default), post item and see marker on activity.
Fixes #128

Fix team Selector design

---

docker-compose.yml
package-lock.json
src/components/news-item.vue

work on news-item issue

---

src/components/news-item.vue

contain rather than cover.

---

package-lock.json
package.json
src/components/activity.vue
src/config/App.vue
src/db/schemas/user.ts

Solved viewpoint-Breaking funnily on middle-size  for  some odd whitespace at width <= 989px when the menu isn't present yet.

Viewpoint-Breaking funnily on middle-size

---

package-lock.json
src/templates/app.html

another  attempt to get codepush to work

---

package-lock.json
package.json
src/components/activity.vue
src/components/edit-team-filter.vue
src/components/team-filter-header.vue
src/stores/auth.ts
src/stores/feed.ts
src/views/Feed.vue
tests/e2e/specs/multi-team-filter.js
tests/e2e/support/commands.js

Rewrite teamfilter

---

src/components/comment.vue

Brief subcomment design fixess

---

src/components/activity.vue
src/components/interaction-bar.vue
src/components/message-entry.vue
src/components/new-post-modal.vue
src/components/new-post.vue
src/components/render-objects.vue
src/components/settings/generic-editor-modal.vue
src/db/schemas/activity.ts
src/db/schemas/message.ts
src/stores/draft.ts
src/stores/inbox.ts
src/views/Feed.vue
src/views/ViewConversation.vue

Implementing extended Conversation Messages

---

.gitignore
.gitpod.Dockerfile
.gitpod.boot_containers.sh
.gitpod.devserver.sh
.gitpod.init.sh
.gitpod.runserver.sh
.gitpod.startup.sh
.gitpod.yml
docker-compose.yml
package-lock.json
src/components/render-objects.vue
src/stores/teams.ts
src/views/Team/Outlet.vue
vue.config.js

Fix issue #186 and show correct content in news and feed
Also GitPod support is added (with small problems). Should not interfere with local development.

feature/webfixes fix #186

---

src/utils/setup.ts

refs #189
Fixes warning when `PushNotifications` capacitor plugin is not available for environment (i.e. web).

Fixing push notifications

---

src/stores/teams.ts
src/views/Team/Outlet.vue

add news & fix feed

---

.github/CONTRIBUTING.md
.gitpod.yml
README.md
package-lock.json
package.json
tests/e2e/specs/notifications-configuration.js

Fixes #200 .
Some times some tests still fail though.
Also:
- Updates cypress to `7.1` (more reliable on gitpod)
- Updates the Docs to mention gitpod setup.

Cypress runs on gitpod

---

.github/workflows/testing.yml
backend/cloud/activity.js
backend/cloud/common.js
backend/cloud/conversations.js
backend/cloud/models/team.js
backend/cloud/objects.js
backend/cloud/teams.js
backend/cloud/user.js
backend/cloud/utils.js
bin/mock-data.js
bin/mock-data/index.ts
src/config/Consts.ts
src/db/schemas/team.ts
src/stores/auth.ts
src/views/ViewUser.vue
tests/e2e/specs/team-joining.js

Implement co-auto-joining

---

src/config/App.vue
src/utils/theme.ts
src/views/settings/General.vue

fixing dark mode forcing

---

backend/cloud/common.js
backend/server.js
src/components/edit-faq.vue
src/components/faq-entry.vue
src/components/like-button.vue
src/views/FAQ.vue
tests/e2e/specs/faq.js
tests/e2e/specs/likes.js
tests/e2e/specs/news.js
tests/e2e/support/commands.js

FAQ fixing

---

.github/workflows/deploy-default-app.yml
backend/cloud/installation.js
bin/mock-data.js
bin/mock-data/index.ts
src/components/activity.vue
src/components/login-modal.vue
src/stores/auth.ts
src/stores/globals.ts
src/templates/app.html
src/views/Feed.vue
vue.config.js

We want to support multiple default teams

---

src/views/News.vue
tests/e2e/specs/news.js

fixes https://github.com/TeamFranka/affinity/issues/234 and https://github.com/TeamFranka/affinity/issues/251

fix: flip back to previous news post

---

src/components/generic/default-back-header.vue
src/router/index.ts
src/views/App.vue
src/views/Donations.vue
src/views/FAQ.vue
src/views/Inbox.vue
src/views/ViewActivity.vue
src/views/ViewTeam.vue
src/views/ViewUser.vue

Move Pages out of Community Outlet, add Back-Button

---

src/components/news-item.vue
src/components/render-objects.vue
src/config/App.vue
src/locales/de.json
src/locales/en.json
src/utils/platform.ts
src/views/my/Main.vue

fixes https://github.com/TeamFranka/affinity/issues/252

fallback for unknown content types

---

.github/workflows/app-affinity.yml
src/components/news-item.vue
tests/e2e/specs/signup.js

slides for multi-content-news-items
